### ISSUE TITLE
Command 'git co cs-lesson1' not working by deafult

### ISSUE THREAD

**Issue by ghost** [pelonpelon/mithril-interactive-tutorial#3]
At the end of the introduction, the command "git co cs-lesson1" should be used. For this to work, you must first add the shorthand form of "git checkout" by running "git config --global alias.co checkout".

I'm not sure at which level you would like me to help you find bugs in the tutorial, so as you can tell, I'll simply add every small thing like this as I find them, let me know if I should filter stuff like this out!

**Comment by pelonpelon** [comment]
Thanks again. I'll change all `git co` to `git checkout`.

I haven't worked on this project for a long time. I've had my doubts about its usefulness since it requires such a very specific setup. And the community is evolving, settling on different patterns to the ones I outline in the tutorial. When Mithril v0.2.1 (branch **next**) is released I'll have to do a major rewrite.

I welcome your comments and issues, and I will correct the quick fixes, but I won't be able to tackle any of the major problems until October.

Thanks.

**Comment by ghost** [comment]
I'm simply using it to get an easy to understand introduction to Mithril. Most likely I will be using pure js rather than coffescript, but the tutorial seems to be using not quite the most simplified syntax that coffecript provides (that I find when looking at e.g. https://gist.github.com/rapind/1e6fe7a24a4513655847). It still looks very similar to pure js; I still get the concepts.

I am also curious about different design-patterns that can be used. I noticed on https://github.com/lhorie/mithril.js/wiki/Components that the module-pattern (assuming this means controller+view = 1 module) is no longer recommended? I will be building an isomorphic app, making https://github.com/StephanHoyer/mithril-isomorphic-example my starting-point, but I will have to be able to use modular component composition, as my project will be quite large.

So right now my aim is to learn the basics of Mithril and somehow figure out how to make an isomorphic app with modular component composition. I'll have to learn both node and Mithril at the same time (coming from php), so basically I'm trying to figure out how to approach these learning curves in a manageable way. Any help, such as this tutorial, is very helpful! :)

**Comment by pelonpelon** [comment]
I have every intention of rewriting the tutorial in JS (es6). I started in CS because I've always found it visually clearer when expressing code logic. However, I avoided many common CS shortcuts that obscure Mithirl logic. The mix was a bad choice on my part.

`m.module` didn't go away. `m.mount` is just a name change.
controller+view = component

Your choice of words, "modular component", is reflective of the current state of affairs. Components are the old modules, with enhancements. You will find many examples and some fully developed applications in the wiki that were written in the pre-component days. These are still useful examples when you clearly understand the difference between the old _module_ and the new _component_.

I advise that you forget the word _module_ with regards to Mithril. In the iso example you cited, `module.exports` is used. This is a node/commonjs packaging term and has nothing to do with Mithril. 
The _module pattern_, a software design pattern, is not a direct corollary to the old Mithril module either. Thus, the name was changed.

**Comment by ghost** [comment]
Thanks, that cleared some things a bit - and complicated some others :)

Just to make sure we're talking about the same thing, when I said "modular component composition", I was referring to a way of composing views from multiple components that can be reused in multiple places, e.g. like it's used in this example: http://jsbin.com/koqomo/5/edit?js,output

Btw, how do you keep track of how Mithril and it's community is evolving? I assume you are very active in the community (watching discussions and changes on github and gitter), or is there some sort of "summary" of what's happening, somewhere? Building something that hopefully will be around for many years, one of my concerns is long-term maintainability. If Mithril changes a lot, it will become difficult to keep track of it.

**Comment by ghost** [comment]
Looking at tutorial 1, I realize that we are talking about the same thing.

Anyway, I've noticed something that strikes me as a bit odd:

In tut 1, you say that a component mustn't return an array. Before reading this, I stared playing around with components in the iso I'm using. If I return an array, it renders fine in node (looks fine if I disable js), but when this is then replaced onload, everything breaks at the point where the component is inserted. If arrays can be used in node, why wouldn't this be possible in client js? Before I read in your tutorial that it mustn't be an array, I thought it was a bug.

Of course I could place everything within a div, but seeing it works in node, I really think it should work on client side as well. Or am I wrong?
